=== tribhu451/3-1D_ideal_hydro/therminator/build/doxygen/figure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="FIGURE">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="LABEL"/>
        <xs:element ref="EVENTS"/>
        <xs:element ref="ENTRIES"/>
        <xs:element maxOccurs="unbounded" ref="HISTOGRAM"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LABEL" type="xs:string"/>
  <xs:element name="EVENTS" type="xs:integer"/>
  <xs:element name="ENTRIES" type="xs:integer"/>
  <xs:element name="HISTOGRAM">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PARTICLE"/>
        <xs:element ref="BINS"/>
        <xs:element ref="DATA"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PARTICLE">
    <xs:complexType mixed="true">
      <xs:attribute name="entries" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BINS">
    <xs:complexType mixed="true">
      <xs:attribute name="number" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DATA">
    <xs:complexType mixed="true">
      <xs:attribute name="points" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tribhu451/3-1D_ideal_hydro/therminator/build/doxygen/figure.xml
<?xml version="1.0" encoding="utf-8"?>
<FIGURE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://therminator2.ifj.edu.pl/figure.xsd">
  <LABEL>dN/(2 #pi p_{T} dp_{T} dy)</LABEL>
  <EVENTS>50000</EVENTS>
  <ENTRIES>128081537</ENTRIES>
  <HISTOGRAM>
    <PARTICLE entries="12186629">#pi^{+}</PARTICLE>
    <BINS number="6">idx	p_{T} [GeV/c]	p_{T} [GeV/c]_[MIN]	p_{T} [GeV/c]_[MAX]	dN/(2 #pi p_{T} dp_{T} dy)	dN/(2 #pi p_{T} dp_{T} dy)_[ERROR]</BINS>
    <DATA points="60">
1	0.025	0	0.05	312.681	1.15577
2	0.075	0.05	0.1	284.994	0.356056
3	0.125	0.1	0.15	240.39	0.249951
4	0.175	0.15	0.2	193.324	0.188687
5	0.225	0.2	0.25	151.442	0.147022
6	0.275	0.25	0.3	118.443	0.117471
7	0.325	0.3	0.35	92.0692	0.0952055
8	0.375	0.35	0.4	72.1462	0.0784206
9	0.425	0.4	0.45	56.6654	0.0652638
10	0.475	0.45	0.5	44.6264	0.0547678
11	0.525	0.5	0.55	35.1735	0.0462407
12	0.575	0.55	0.6	28.0426	0.039446
13	0.625	0.6	0.65	22.2559	0.033702
14	0.675	0.65	0.7	17.6974	0.0289161
15	0.725	0.7	0.75	14.1062	0.0249078
16	0.775	0.75	0.8	11.2244	0.0214881
17	0.825	0.8	0.85	9.02738	0.0186764
18	0.875	0.85	0.9	7.22194	0.0162198
19	0.925	0.9	0.95	5.80855	0.0141471
20	0.975	0.95	1	4.64983	0.0123278
21	1.025	1	1.05	3.74465	0.0107895
22	1.075	1.05	1.1	3.02225	0.00946482
23	1.125	1.1	1.15	2.44622	0.00832377
24	1.175	1.15	1.2	1.95578	0.00728222
25	1.225	1.2	1.25	1.58136	0.00641319
26	1.275	1.25	1.3	1.27776	0.00565047
27	1.325	1.3	1.35	1.03461	0.00498731
28	1.375	1.35	1.4	0.83853	0.00440758
29	1.425	1.4	1.45	0.678467	0.00389442
30	1.475	1.45	1.5	0.550801	0.00344881
31	1.525	1.5	1.55	0.443092	0.00304222
32	1.575	1.55	1.6	0.361347	0.00270314
33	1.625	1.6	1.65	0.292905	0.00239621
34	1.675	1.65	1.7	0.240549	0.00213865
35	1.725	1.7	1.75	0.198182	0.00191293
36	1.775	1.75	1.8	0.158447	0.00168614
37	1.825	1.8	1.85	0.130114	0.0015069
38	1.875	1.85	1.9	0.109045	0.00136087
39	1.925	1.9	1.95	0.086511	0.00119628
40	1.975	1.95	2	0.0703015	0.00106459
41	2.025	2	2.05	0.0591885	0.000964769
42	2.075	2.05	2.1	0.0468039	0.000847505
43	2.125	2.1	2.15	0.0383544	0.000758063
44	2.175	2.15	2.2	0.0308519	0.000672138
45	2.225	2.2	2.25	0.0256472	0.000605872
46	2.275	2.25	2.3	0.0208848	0.000540697
47	2.325	2.3	2.35	0.0174198	0.000488436
48	2.375	2.35	2.4	0.0141184	0.000435089
49	2.425	2.4	2.45	0.0114121	0.000387137
50	2.475	2.45	2.5	0.00984342	0.000355895
51	2.525	2.5	2.55	0.00797016	0.000317041
52	2.575	2.55	2.6	0.00615926	0.000276007
53	2.625	2.6	2.65	0.00505887	0.000247738
54	2.675	2.65	2.7	0.00383566	0.000213756
55	2.725	2.7	2.75	0.00283888	0.000182117
56	2.775	2.75	2.8	0.00289388	0.0001823
57	2.825	2.8	2.85	0.00232158	0.000161754
58	2.875	2.85	2.9	0.00176181	0.000139722
59	2.925	2.9	2.95	0.00149195	0.000127467
60	2.975	2.95	3	0.00145564	0.000124821
    </DATA>
  </HISTOGRAM>
  <HISTOGRAM>
    <PARTICLE entries="1973061">K^{+}</PARTICLE>
    <BINS number="6">idx	p_{T} [GeV/c]	p_{T} [GeV/c]_[MIN]	p_{T} [GeV/c]_[MAX]	dN/(2 #pi p_{T} dp_{T} dy)	dN/(2 #pi p_{T} dp_{T} dy)_[ERROR]</BINS>
    <DATA points="60">
1	0.025	0	0.05	15.4198	0.226898
2	0.075	0.05	0.1	14.9873	0.0813309
3	0.125	0.1	0.15	14.4954	0.0612064
4	0.175	0.15	0.2	13.9001	0.0504999
5	0.225	0.2	0.25	13.094	0.0431557
6	0.275	0.25	0.3	12.1735	0.0376176
7	0.325	0.3	0.35	11.1359	0.0330804
8	0.375	0.35	0.4	10.004	0.0291797
9	0.425	0.4	0.45	8.92937	0.0258929
10	0.475	0.45	0.5	7.92849	0.0230752
11	0.525	0.5	0.55	6.88246	0.0204459
12	0.575	0.55	0.6	5.94597	0.0181568
13	0.625	0.6	0.65	5.12743	0.0161727
14	0.675	0.65	0.7	4.38245	0.0143858
15	0.725	0.7	0.75	3.73652	0.0128167
16	0.775	0.75	0.8	3.15988	0.0113988
17	0.825	0.8	0.85	2.67508	0.0101657
18	0.875	0.85	0.9	2.26977	0.00909174
19	0.925	0.9	0.95	1.88176	0.00805108
20	0.975	0.95	1	1.59239	0.00721372
21	1.025	1	1.05	1.33927	0.00645198
22	1.075	1.05	1.1	1.10748	0.00572885
23	1.125	1.1	1.15	0.929981	0.00513155
24	1.175	1.15	1.2	0.778213	0.00459335
25	1.225	1.2	1.25	0.642704	0.00408822
26	1.275	1.25	1.3	0.533611	0.00365142
27	1.325	1.3	1.35	0.446128	0.00327488
28	1.375	1.35	1.4	0.370413	0.00292944
29	1.425	1.4	1.45	0.302217	0.00259918
30	1.475	1.45	1.5	0.251225	0.00232916
31	1.525	1.5	1.55	0.208271	0.00208562
32	1.575	1.55	1.6	0.172424	0.00186732
33	1.625	1.6	1.65	0.147885	0.00170248
34	1.675	1.65	1.7	0.120301	0.00151246
35	1.725	1.7	1.75	0.100604	0.00136292
36	1.775	1.75	1.8	0.0824943	0.00121648
37	1.825	1.8	1.85	0.0671883	0.00108273
38	1.875	1.85	1.9	0.0563915	0.000978571
39	1.925	1.9	1.95	0.0457294	0.00086968
40	1.975	1.95	2	0.0379577	0.000782362
41	2.025	2	2.05	0.0319649	0.000708951
42	2.075	2.05	2.1	0.0269605	0.000643209
43	2.125	2.1	2.15	0.0221598	0.000576223
44	2.175	2.15	2.2	0.0179819	0.000513152
45	2.225	2.2	2.25	0.0142379	0.000451382
46	2.275	2.25	2.3	0.0125847	0.000419733
47	2.325	2.3	2.35	0.00935396	0.000357927
48	2.375	2.35	2.4	0.00820175	0.000331543
49	2.425	2.4	2.45	0.00656381	0.000293548
50	2.475	2.45	2.5	0.00581149	0.000273354
51	2.525	2.5	2.55	0.00408492	0.000226944
52	2.575	2.55	2.6	0.00398377	0.00022201
53	2.625	2.6	2.65	0.00360413	0.000209136
54	2.675	2.65	2.7	0.00284495	0.000184027
55	2.725	2.7	2.75	0.00252531	0.000171828
56	2.775	2.75	2.8	0.0019737	0.000150495
57	2.825	2.8	2.85	0.00164491	0.000136135
58	2.875	2.85	2.9	0.00113894	0.000112225
59	2.925	2.9	2.95	0.000958586	0.000102187
60	2.975	2.95	3	0.000845141	9.50867e-05
    </DATA>
  </HISTOGRAM>
  <HISTOGRAM>
    <PARTICLE entries="673392">p</PARTICLE>
    <BINS number="6">idx	p_{T} [GeV/c]	p_{T} [GeV/c]_[MIN]	p_{T} [GeV/c]_[MAX]	dN/(2 #pi p_{T} dp_{T} dy)	dN/(2 #pi p_{T} dp_{T} dy)_[ERROR]</BINS>
    <DATA points="60">
1	0.025	0	0.05	2.23923	0.07371
2	0.075	0.05	0.1	2.32954	0.0321993
3	0.125	0.1	0.15	2.364	0.0246858
4	0.175	0.15	0.2	2.29971	0.0205156
5	0.225	0.2	0.25	2.27951	0.0179976
6	0.275	0.25	0.3	2.17762	0.0159006
7	0.325	0.3	0.35	2.13919	0.0144925
8	0.375	0.35	0.4	2.08511	0.0133217
9	0.425	0.4	0.45	1.97895	0.0121841
10	0.475	0.45	0.5	1.90734	0.0113127
11	0.525	0.5	0.55	1.80413	0.010465
12	0.575	0.55	0.6	1.66031	0.00959446
13	0.625	0.6	0.65	1.57024	0.00894672
14	0.675	0.65	0.7	1.44243	0.00825162
15	0.725	0.7	0.75	1.33111	0.00764826
16	0.775	0.75	0.8	1.21227	0.00705898
17	0.825	0.8	0.85	1.08956	0.00648602
18	0.875	0.85	0.9	0.985416	0.00598966
19	0.925	0.9	0.95	0.881226	0.00550855
20	0.975	0.95	1	0.791534	0.00508526
21	1.025	1	1.05	0.703868	0.00467673
22	1.075	1.05	1.1	0.616474	0.00427373
23	1.125	1.1	1.15	0.551343	0.00395111
24	1.175	1.15	1.2	0.483626	0.00362094
25	1.225	1.2	1.25	0.41551	0.00328677
26	1.275	1.25	1.3	0.367564	0.00302975
27	1.325	1.3	1.35	0.317945	0.00276459
28	1.375	1.35	1.4	0.274895	0.00252328
29	1.425	1.4	1.45	0.234821	0.00229097
30	1.475	1.45	1.5	0.203699	0.0020972
31	1.525	1.5	1.55	0.173205	0.00190194
32	1.575	1.55	1.6	0.151478	0.00175013
33	1.625	1.6	1.65	0.126595	0.00157513
34	1.675	1.65	1.7	0.109225	0.00144097
35	1.725	1.7	1.75	0.0919244	0.00130266
36	1.775	1.75	1.8	0.0796889	0.0011957
37	1.825	1.8	1.85	0.0668378	0.00107989
38	1.875	1.85	1.9	0.0572321	0.000985911
39	1.925	1.9	1.95	0.0487871	0.00089827
40	1.975	1.95	2	0.0406337	0.000809464
41	2.025	2	2.05	0.0346899	0.000738604
42	2.075	2.05	2.1	0.0291225	0.000668483
43	2.125	2.1	2.15	0.0244592	0.000605469
44	2.175	2.15	2.2	0.0197631	0.000537894
45	2.225	2.2	2.25	0.0177914	0.000504643
46	2.275	2.25	2.3	0.0151699	0.000460762
47	2.325	2.3	2.35	0.0116518	0.000399425
48	2.375	2.35	2.4	0.0107157	0.000379101
49	2.425	2.4	2.45	0.00860281	0.000336146
50	2.475	2.45	2.5	0.00706291	0.000301442
51	2.525	2.5	2.55	0.00603785	0.000275881
52	2.575	2.55	2.6	0.00510738	0.000251322
53	2.625	2.6	2.65	0.00423368	0.000226627
54	2.675	2.65	2.7	0.00332317	0.000198956
55	2.725	2.7	2.75	0.00274577	0.000179117
56	2.775	2.75	2.8	0.00255783	0.000171287
57	2.825	2.8	2.85	0.00215337	0.000155814
58	2.875	2.85	2.9	0.001818	0.000141964
59	2.925	2.9	2.95	0.00139175	0.000123015
60	2.975	2.95	3	0.0011553	0.00011117
    </DATA>
  </HISTOGRAM>
</FIGURE>
